### PR TITLE
Fix file hooks when source option is used

### LINKED ISSUE #1498: Inconsistent file hook handling between "content" and "source" options
## Describe the bug

When using `file $target, content => $content;`, Rex creates a temporary file on the managed host first, then renames that into the actual target file. It also runs `before_change` and `after_change` file hooks around the rename operation.

But when using `file $target, source => $source;`, Rex reuses `Rex::Commands::Upload::upload();` to simply do a file upload without the need for the temporary file, and relies on all the _upload_ hooks, so no `before_change` and `after_change` _file_ hooks are being run.

This leads to inconsistent behavior from the perspective of the `file` resource, and makes it harder than necessary to develop various hooks.

## How to reproduce it

1. Specify a `before_change` file hook.
2. Manage a file with the `content` option, and the above hook will be triggered.
3. Manage a file with the `source` option, and the above hook will not be triggered.

Shortest code example that demonstrates the bug:

```perl
use Rex -feature => [qw(1.4 exec_autodie)];

use Rex::Hook;
use DDP;

register_function_hooks {
    before        => { file => \&my_before_hook },
    before_change => { file => \&my_before_change_hook },
    after_change  => { file => \&my_after_change_hook },
    after         => { file => \&my_after_hook },
};

sub my_before_hook {
    say '-' x 20;
    say 'before_hook';
    p @_;
}

sub my_before_change_hook {
    say 'before_change hook';
}

sub my_after_change_hook {
    say 'after_change hook';
}

sub my_after_hook {
    say 'after_hook';
    say '-' x 20;
}

task 'inconsistent_hook', sub {
    file '/tmp/1', content => '1';
    file '/tmp/2', source  => 'Rexfile';
    unlink '/tmp/1', '/tmp/2';
};
```

## Expected behavior

I would expect `before_change` and `after_change` file hooks to be executed even for `file $target, source => $source;` cases. For even greater consistency, the same "upload temporary file first, then rename it into target" approach could be used too.

## Circumstances

 - Rex version: 1.13.3
 - Perl version: 5.34.0
 - OS running rex: Gentoo
 - OS managed by rex: Gentoo
 - How rex was installed: `dzil install`

### PR DESCRIPTION
**Pull request by ferki**
This PR is an attempt to fix #1498 by making sure that the file command's `source` option takes the same code path as `content`. This ensures having a temporary file created first, which is then moved to the final location. It also enables `before_change` and `after_change` hooks for the `source` option.

Both of these changes increase the consistency of the file commands behavior across the variety of available options.

## Checklist

- [x] based on top of latest source code 
- [x] changelog entry included 
- [x] tests pass in CI 
- [x] git history is clean 
- [x] git commit messages are [well-written](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

File: lib/Rex/Commands/File.pm [hunk 1]
```diff
@@ -552,15 +558,6 @@ sub file {
...
 
   }
-  elsif ( exists $option->{"source"} && !$is_directory ) {
-    $option->{source} =
-      Rex::Helper::Path::get_file_path( $option->{source}, caller() );
-
-    # HOOKS: for this case you have to use the upload hooks!
-    $__ret = upload $option->{"source"}, "$file", force => 1;
-
-    $need_md5 = 0 if $__ret->{changed} == 0;
```
Comment (ehuelsmann) [inline lib/Rex/Commands/File.pm:562]: At first I wondered why `$need_md5` doesn't need to be set in the merged codepath. However, the merged code path turns out to have its own changed-ness detection (through md5s, but not through "need_md5". (thanks for answering my questions on IRC).

**Review by ehuelsmann — APPROVED** [review]
All in all a very nice cleanup both of the test suite as well as for the `file` command.
